spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**

        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**, /api/v1/cars/**

        - id: rides-service
          uri: lb://rides-service
          predicates:
            - Path=/api/v1/rides/**

        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/api/v1/ratings/**
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8081/eureka}


management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
