spring:
  application:
    name: rides-service

  data:
    mongodb:
      uri: ${DB_URI:mongodb://werdiens:haduken@localhost:27017/RideDB?authSource=admin}


  cloud:
    openfeign:
      client:
        config:
          routing-service:
            url: https://graphhopper.com/api/1

api:
  key: ${APIKEY:2dda7d03-6d64-4f4e-85b2-e17672cb09fa}
server:
  port: 5003

eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8081/eureka}


