spring:
  application:
    name: rides-service
  data:
    mongodb:
      uri: ${URI:mongodb://werdiens:haduken@localhost:27017/RideDB?authSource=admin}

api:
  key: ${APIKEY:2dda7d03-6d64-4f4e-85b2-e17672cb09fa}
server:
  port: 8080