spring:
  application:
    name: rides-service


  data:
    mongodb:
      database: testdb

  cloud:
    openfeign:
      client:
        config:
          passenger-service-test:
            url: http://localhost:8090/api/v1/passengers
          driver-service-test:
            url: http://localhost:8090/api/v1/drivers
          routing-service-test:
            url: http://localhost:8090//graphhopper.com/api

api:
  key: ${APIKEY:2dda7d03-6d64-4f4e-85b2-e17672cb09fa}


resilience4j:
  circuitbreaker:
    instances:
      driver-service-breaker:
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 5s