spring:
  application:
    name: rides-service
  data:
    mongodb:
      host: ${HOST_DB:localhost}
      port: ${PORT_DB:27017}
      database: ${DB_NAME:RideDB}
      username: ${USERNAME:werdiens}
      password: ${USERNAME:haduken}


api:
  key: ${APIKEY:2dda7d03-6d64-4f4e-85b2-e17672cb09fa}
server:
  port: 8081