spring:
  application:
    name: rating-service

  data:
    mongodb:
      uri: ${DB_URI:mongodb://werdiens:haduken@localhost:27017/RatingDB?authSource=admin}

  kafka:
    bootstrap-servers: ${BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      driver-rating: update-rating-topic
      passenger-rating: update-passenger-rating-topic


eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8081/eureka}

server:
  port: 5004