spring:
  application:
    name: rating-service
  data:
    mongodb:
      host: ${HOST_DB:localhost}
      port: ${PORT_DB:27017}
      database: ${DB_NAME:RatingDB}
      username: werdiens
      password: haduken
      authenticationDatabase: admin