spring:
  application:
    name: rating-service

  data:
    mongodb:
      uri: ${DB_URI:mongodb://werdiens:haduken@localhost:27017/RatingDB?authSource=admin}

  cloud:
    openfeign:
      client:
        config:
          driver-service:
            url: localhost:8082/api/v1/drivers
          passenger-service:
            url: localhost:8081/api/v1/passengers
          rides-service:
            url: localhost:8083/api/v1/rides