spring:
  application:
    name: rating-service

  data:
    mongodb:
      host: ${HOST_DB:localhost}
      port: ${PORT_DB:27017}
      database: ${DB_NAME:RatingDB}
      username: werdiens
      password: haduken
      authenticationDatabase: admin

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      driver-rating: update-rating-topic
      passenger-rating: update-passenger-rating-topic


  cloud:
    openfeign:
      client:
        config:
          driver-service:
            url: localhost:8083/api/v1/drivers
          passenger-service:
            url: localhost:8081/api/v1/passengers
          rides-service:
            url: localhost:8082/api/v1/rides
