server:
  port: 8080


spring:
  application:
    name: driver-service
  datasource:
      driver-class-name: ${DB-DRIVER:org.postgresql.Driver}
      url: ${DB-URL:jdbc:postgresql://localhost:5432/driverdb}
      username: ${DB-USERNAME:root}
      password: ${DB-PASSWORD:123}
  jpa:
    database: ${DB:postgresql}
    hibernate:
      ddl-auto: validate

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: rating-consumer
      auto-offset-reset: earliest


