create table if not exists passengers(
id int primary key generated by default as identity,
name varchar(255) not null,
second_name varchar(255) not null,
email varchar(255) not null,
phone_number varchar(255) not null,
is_deleted boolean not null
);