server:
  port: 8080

spring:
  application:
    name: passenger-service

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  profiles:
    active: dev