server:
  port: 8080

spring:
  application:
    name: passenger-service

  datasource:
    driver-class-name: ${DB-DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/passenger_db}
    username: ${DB-USERNAME:root}
    password: ${DB-PASSWORD:123}

  jpa:
    database: ${DB:postgresql}
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: rating-consumer-1
      auto-offset-reset: earliest

  active:
    profiles: test