server:
  port: 8080

spring:
  application:
    name: passenger-service

  datasource:
    driver-class-name: ${DB-DRIVER:org.postgresql.Driver}
    url: ${DB-URL:jdbc:postgresql://localhost:5432/PassengerDB}
    username: ${DB-USERNAME:postgres}
    password: ${DB-PASSWORD:postgres}
  jpa:
    database: ${DB:postgresql}
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: rating-consumer-1
      auto-offset-reset: earliest
