server:
  port: 8080
spring:
  application:
    name: passenger-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PassengerDB
    username: root
    password: 123
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
